SUM     START   400FH
FIRST   LDX ZERO
    	LDA ZERO
LOOP    ADD TABLE, X
    TIX COUNT
    JLT LOOP
    STA TOTAL
RSUB
TABLE   BYTE    C'hola'
TABLE   RESW    FH
COUNT   RESW    10
ZERO    WORD    0
TOTAL   RESW    1
    END     FIRST