SUM     START   400FH
FIRST   LDX ZERO
        LDA ZERO
LOOP    ADD TABLE, X
    TIX COUNT
    JLT LOOP
    STA TOTAL
RSUB
TABLE   BYTE    C'hola'
TABLON   BYTE    X'000'
TABLOa   BYTE    X'f0'
TABLE   RESW    0H
COUNT   RESW    10
ZERO    WORD    0
ZERO    WORD    10
ZERO    WORD    FH
TOTAL   RESW    2
TOTAL   RESW    AH
    END     FIRST