SUM     START   400FH
RSUB
FIRST   LDX ZERO
        LDA ZERO
LOOP    ADD TABLE, X
    TIX COUNT
COUNT   RESW    10
    JLT LOOP
    STA TOTAL
TABLE   BYTE    C'hola'
TABLON   BYTE    X'000'
TABLOa   BYTE    X'F0'
TABLE   RESW    5H
ZERO    WORD    0
ZERO    WORD    10
ZERO    WORD    FH
TOTAL   RESW    2
TOTAL   RESW    AH
    END