SUM START   0H
FIRST   LDX #0
    LDA #0
    +LDB    #TABLEUNO
    BASE    TABLEDOS
LOOP    ADD TABLEUNO,X
    ADD TABLEDOS,X
    TIX COUNT
    JLT LOOP
    RMO A, L
    SHIFTR  A, 2H
    +STA    TOTAL
    CLEAR   A
COUNT   RESW    1
TABLEUNO  RESW    2000
TABLEDOS  RESW    2000
TOTAL   RESW    2000
    END FIRST