//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\SicGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISicGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class SicGrammarBaseListener : ISicGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SicGrammarParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrograma([NotNull] SicGrammarParser.ProgramaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SicGrammarParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrograma([NotNull] SicGrammarParser.ProgramaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SicGrammarParser.inicio"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInicio([NotNull] SicGrammarParser.InicioContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SicGrammarParser.inicio"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInicio([NotNull] SicGrammarParser.InicioContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SicGrammarParser.fin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFin([NotNull] SicGrammarParser.FinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SicGrammarParser.fin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFin([NotNull] SicGrammarParser.FinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SicGrammarParser.proposicion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProposicion([NotNull] SicGrammarParser.ProposicionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SicGrammarParser.proposicion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProposicion([NotNull] SicGrammarParser.ProposicionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SicGrammarParser.instruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruccion([NotNull] SicGrammarParser.InstruccionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SicGrammarParser.instruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruccion([NotNull] SicGrammarParser.InstruccionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SicGrammarParser.directiva"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectiva([NotNull] SicGrammarParser.DirectivaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SicGrammarParser.directiva"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectiva([NotNull] SicGrammarParser.DirectivaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SicGrammarParser.opinstruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpinstruccion([NotNull] SicGrammarParser.OpinstruccionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SicGrammarParser.opinstruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpinstruccion([NotNull] SicGrammarParser.OpinstruccionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
