//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\SicGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class SicGrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, INSTRUCCIONES=5, TIPODIRECTIVA=6, BYTE=7, 
		START=8, NUMD=9, OPDIRECTIVA=10, FINL=11, NUMH=12, ID=13, SEP=14, RSUB=15;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "INSTRUCCIONES", "TIPODIRECTIVA", "BYTE", 
		"START", "NUMD", "OPDIRECTIVA", "FINL", "NUMH", "ID", "SEP", "RSUB"
	};


	public SicGrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SicGrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'h'", "'H'", "'END'", "',X'", null, null, null, "'START'", null, 
		null, "'\n'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "INSTRUCCIONES", "TIPODIRECTIVA", "BYTE", 
		"START", "NUMD", "OPDIRECTIVA", "FINL", "NUMH", "ID", "SEP", "RSUB"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SicGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SicGrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x11', '\xC2', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', 'l', '\n', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x5', '\a', 'z', '\n', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', 
		'\b', '\x8E', '\n', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', '\v', '\x9C', '\n', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x6', '\r', '\xA2', 
		'\n', '\r', '\r', '\r', '\xE', '\r', '\xA3', '\x3', '\xE', '\x6', '\xE', 
		'\xA7', '\n', '\xE', '\r', '\xE', '\xE', '\xE', '\xA8', '\x3', '\xE', 
		'\a', '\xE', '\xAC', '\n', '\xE', '\f', '\xE', '\xE', '\xE', '\xAF', '\v', 
		'\xE', '\x6', '\xE', '\xB1', '\n', '\xE', '\r', '\xE', '\xE', '\xE', '\xB2', 
		'\x3', '\xF', '\x6', '\xF', '\xB6', '\n', '\xF', '\r', '\xF', '\xE', '\xF', 
		'\xB7', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x5', '\x10', '\xC1', '\n', '\x10', 
		'\x2', '\x2', '\x11', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', 
		'\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', 
		'\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', 
		'\x11', '\x3', '\x2', '\x5', '\x4', '\x2', 'J', 'J', 'j', 'j', '\x4', 
		'\x2', '\x43', '\\', '\x63', '|', '\x4', '\x2', '\v', '\v', '\"', '\"', 
		'\x2', '\xE0', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x5', '#', '\x3', '\x2', '\x2', '\x2', 
		'\a', '%', '\x3', '\x2', '\x2', '\x2', '\t', ')', '\x3', '\x2', '\x2', 
		'\x2', '\v', 'k', '\x3', '\x2', '\x2', '\x2', '\r', 'y', '\x3', '\x2', 
		'\x2', '\x2', '\xF', '{', '\x3', '\x2', '\x2', '\x2', '\x11', '\x8F', 
		'\x3', '\x2', '\x2', '\x2', '\x13', '\x95', '\x3', '\x2', '\x2', '\x2', 
		'\x15', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x17', '\x9D', '\x3', '\x2', 
		'\x2', '\x2', '\x19', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x1B', '\xB0', 
		'\x3', '\x2', '\x2', '\x2', '\x1D', '\xB5', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', '\xB9', '\x3', '\x2', '\x2', '\x2', '!', '\"', '\a', 'j', '\x2', 
		'\x2', '\"', '\x4', '\x3', '\x2', '\x2', '\x2', '#', '$', '\a', 'J', '\x2', 
		'\x2', '$', '\x6', '\x3', '\x2', '\x2', '\x2', '%', '&', '\a', 'G', '\x2', 
		'\x2', '&', '\'', '\a', 'P', '\x2', '\x2', '\'', '(', '\a', '\x46', '\x2', 
		'\x2', '(', '\b', '\x3', '\x2', '\x2', '\x2', ')', '*', '\a', '.', '\x2', 
		'\x2', '*', '+', '\a', 'Z', '\x2', '\x2', '+', '\n', '\x3', '\x2', '\x2', 
		'\x2', ',', '-', '\a', '\x43', '\x2', '\x2', '-', '.', '\a', '\x46', '\x2', 
		'\x2', '.', 'l', '\a', '\x46', '\x2', '\x2', '/', '\x30', '\a', '\x43', 
		'\x2', '\x2', '\x30', '\x31', '\a', 'P', '\x2', '\x2', '\x31', 'l', '\a', 
		'\x46', '\x2', '\x2', '\x32', '\x33', '\a', '\x45', '\x2', '\x2', '\x33', 
		'\x34', '\a', 'Q', '\x2', '\x2', '\x34', '\x35', '\a', 'O', '\x2', '\x2', 
		'\x35', 'l', '\a', 'R', '\x2', '\x2', '\x36', '\x37', '\a', '\x46', '\x2', 
		'\x2', '\x37', '\x38', '\a', 'K', '\x2', '\x2', '\x38', 'l', '\a', 'X', 
		'\x2', '\x2', '\x39', 'l', '\a', 'L', '\x2', '\x2', ':', ';', '\a', 'L', 
		'\x2', '\x2', ';', '<', '\a', 'G', '\x2', '\x2', '<', 'l', '\a', 'S', 
		'\x2', '\x2', '=', '>', '\a', 'L', '\x2', '\x2', '>', '?', '\a', 'U', 
		'\x2', '\x2', '?', '@', '\a', 'W', '\x2', '\x2', '@', 'l', '\a', '\x44', 
		'\x2', '\x2', '\x41', '\x42', '\a', 'N', '\x2', '\x2', '\x42', '\x43', 
		'\a', '\x46', '\x2', '\x2', '\x43', 'l', '\a', '\x43', '\x2', '\x2', '\x44', 
		'\x45', '\a', 'N', '\x2', '\x2', '\x45', '\x46', '\a', '\x46', '\x2', 
		'\x2', '\x46', 'G', '\a', '\x45', '\x2', '\x2', 'G', 'l', '\a', 'J', '\x2', 
		'\x2', 'H', 'I', '\a', 'N', '\x2', '\x2', 'I', 'J', '\a', '\x46', '\x2', 
		'\x2', 'J', 'l', '\a', 'N', '\x2', '\x2', 'K', 'L', '\a', 'N', '\x2', 
		'\x2', 'L', 'M', '\a', '\x46', '\x2', '\x2', 'M', 'l', '\a', 'Z', '\x2', 
		'\x2', 'N', 'O', '\a', 'O', '\x2', '\x2', 'O', 'P', '\a', 'W', '\x2', 
		'\x2', 'P', 'l', '\a', 'N', '\x2', '\x2', 'Q', 'R', '\a', 'Q', '\x2', 
		'\x2', 'R', 'l', '\a', 'T', '\x2', '\x2', 'S', 'T', '\a', 'T', '\x2', 
		'\x2', 'T', 'l', '\a', '\x46', '\x2', '\x2', 'U', 'V', '\a', 'U', '\x2', 
		'\x2', 'V', 'W', '\a', 'V', '\x2', '\x2', 'W', 'l', '\a', '\x43', '\x2', 
		'\x2', 'X', 'Y', '\a', 'U', '\x2', '\x2', 'Y', 'Z', '\a', 'V', '\x2', 
		'\x2', 'Z', '[', '\a', '\x45', '\x2', '\x2', '[', 'l', '\a', 'J', '\x2', 
		'\x2', '\\', ']', '\a', 'U', '\x2', '\x2', ']', '^', '\a', 'V', '\x2', 
		'\x2', '^', 'l', '\a', 'N', '\x2', '\x2', '_', '`', '\a', 'U', '\x2', 
		'\x2', '`', '\x61', '\a', 'V', '\x2', '\x2', '\x61', '\x62', '\a', 'U', 
		'\x2', '\x2', '\x62', 'l', '\a', 'Y', '\x2', '\x2', '\x63', '\x64', '\a', 
		'U', '\x2', '\x2', '\x64', '\x65', '\a', 'V', '\x2', '\x2', '\x65', 'l', 
		'\a', 'Z', '\x2', '\x2', '\x66', 'g', '\a', 'U', '\x2', '\x2', 'g', 'h', 
		'\a', 'W', '\x2', '\x2', 'h', 'l', '\a', '\x44', '\x2', '\x2', 'i', 'j', 
		'\a', 'V', '\x2', '\x2', 'j', 'l', '\a', '\x46', '\x2', '\x2', 'k', ',', 
		'\x3', '\x2', '\x2', '\x2', 'k', '/', '\x3', '\x2', '\x2', '\x2', 'k', 
		'\x32', '\x3', '\x2', '\x2', '\x2', 'k', '\x36', '\x3', '\x2', '\x2', 
		'\x2', 'k', '\x39', '\x3', '\x2', '\x2', '\x2', 'k', ':', '\x3', '\x2', 
		'\x2', '\x2', 'k', '=', '\x3', '\x2', '\x2', '\x2', 'k', '\x41', '\x3', 
		'\x2', '\x2', '\x2', 'k', '\x44', '\x3', '\x2', '\x2', '\x2', 'k', 'H', 
		'\x3', '\x2', '\x2', '\x2', 'k', 'K', '\x3', '\x2', '\x2', '\x2', 'k', 
		'N', '\x3', '\x2', '\x2', '\x2', 'k', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'k', 'S', '\x3', '\x2', '\x2', '\x2', 'k', 'U', '\x3', '\x2', '\x2', '\x2', 
		'k', 'X', '\x3', '\x2', '\x2', '\x2', 'k', '\\', '\x3', '\x2', '\x2', 
		'\x2', 'k', '_', '\x3', '\x2', '\x2', '\x2', 'k', '\x63', '\x3', '\x2', 
		'\x2', '\x2', 'k', '\x66', '\x3', '\x2', '\x2', '\x2', 'k', 'i', '\x3', 
		'\x2', '\x2', '\x2', 'l', '\f', '\x3', '\x2', '\x2', '\x2', 'm', 'n', 
		'\a', 'Y', '\x2', '\x2', 'n', 'o', '\a', 'Q', '\x2', '\x2', 'o', 'p', 
		'\a', 'T', '\x2', '\x2', 'p', 'z', '\a', '\x46', '\x2', '\x2', 'q', 'r', 
		'\a', 'T', '\x2', '\x2', 'r', 's', '\a', 'G', '\x2', '\x2', 's', 't', 
		'\a', 'U', '\x2', '\x2', 't', 'z', '\a', '\x44', '\x2', '\x2', 'u', 'v', 
		'\a', 'T', '\x2', '\x2', 'v', 'w', '\a', 'G', '\x2', '\x2', 'w', 'x', 
		'\a', 'U', '\x2', '\x2', 'x', 'z', '\a', 'Y', '\x2', '\x2', 'y', 'm', 
		'\x3', '\x2', '\x2', '\x2', 'y', 'q', '\x3', '\x2', '\x2', '\x2', 'y', 
		'u', '\x3', '\x2', '\x2', '\x2', 'z', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'{', '|', '\a', '\x44', '\x2', '\x2', '|', '}', '\a', '[', '\x2', '\x2', 
		'}', '~', '\a', 'V', '\x2', '\x2', '~', '\x7F', '\a', 'G', '\x2', '\x2', 
		'\x7F', '\x80', '\x3', '\x2', '\x2', '\x2', '\x80', '\x8D', '\x5', '\x1D', 
		'\xF', '\x2', '\x81', '\x82', '\a', '\x45', '\x2', '\x2', '\x82', '\x83', 
		'\a', ')', '\x2', '\x2', '\x83', '\x84', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\x85', '\x5', '\x1B', '\xE', '\x2', '\x85', '\x86', '\a', ')', '\x2', 
		'\x2', '\x86', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\a', 
		'Z', '\x2', '\x2', '\x88', '\x89', '\a', ')', '\x2', '\x2', '\x89', '\x8A', 
		'\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x5', '\x19', '\r', '\x2', 
		'\x8B', '\x8C', '\a', ')', '\x2', '\x2', '\x8C', '\x8E', '\x3', '\x2', 
		'\x2', '\x2', '\x8D', '\x81', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x87', 
		'\x3', '\x2', '\x2', '\x2', '\x8E', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'\x8F', '\x90', '\a', 'U', '\x2', '\x2', '\x90', '\x91', '\a', 'V', '\x2', 
		'\x2', '\x91', '\x92', '\a', '\x43', '\x2', '\x2', '\x92', '\x93', '\a', 
		'T', '\x2', '\x2', '\x93', '\x94', '\a', 'V', '\x2', '\x2', '\x94', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\x4', '\x32', ';', '\x2', 
		'\x96', '\x14', '\x3', '\x2', '\x2', '\x2', '\x97', '\x9C', '\x5', '\x13', 
		'\n', '\x2', '\x98', '\x99', '\x5', '\x19', '\r', '\x2', '\x99', '\x9A', 
		'\t', '\x2', '\x2', '\x2', '\x9A', '\x9C', '\x3', '\x2', '\x2', '\x2', 
		'\x9B', '\x97', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x98', '\x3', '\x2', 
		'\x2', '\x2', '\x9C', '\x16', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', 
		'\a', '\f', '\x2', '\x2', '\x9E', '\x18', '\x3', '\x2', '\x2', '\x2', 
		'\x9F', '\xA2', '\x5', '\x13', '\n', '\x2', '\xA0', '\xA2', '\x4', '\x43', 
		'H', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA0', 
		'\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\x3', '\x2', '\x2', '\x2', 
		'\xA3', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x3', '\x2', 
		'\x2', '\x2', '\xA4', '\x1A', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA7', 
		'\t', '\x3', '\x2', '\x2', '\xA6', '\xA5', '\x3', '\x2', '\x2', '\x2', 
		'\xA7', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA6', '\x3', '\x2', 
		'\x2', '\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAD', 
		'\x3', '\x2', '\x2', '\x2', '\xAA', '\xAC', '\x4', '\x32', ';', '\x2', 
		'\xAB', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAF', '\x3', '\x2', 
		'\x2', '\x2', '\xAD', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', 
		'\x3', '\x2', '\x2', '\x2', '\xAE', '\xB1', '\x3', '\x2', '\x2', '\x2', 
		'\xAF', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xA6', '\x3', '\x2', 
		'\x2', '\x2', '\xB1', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB0', 
		'\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\x3', '\x2', '\x2', '\x2', 
		'\xB3', '\x1C', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB6', '\t', '\x4', 
		'\x2', '\x2', '\xB5', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', 
		'\x3', '\x2', '\x2', '\x2', '\xB7', '\xB5', '\x3', '\x2', '\x2', '\x2', 
		'\xB7', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xB8', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', '\xB9', '\xBA', '\x5', '\x1D', '\xF', '\x2', '\xBA', '\xBB', 
		'\a', 'T', '\x2', '\x2', '\xBB', '\xBC', '\a', 'U', '\x2', '\x2', '\xBC', 
		'\xBD', '\a', 'W', '\x2', '\x2', '\xBD', '\xBE', '\a', '\x44', '\x2', 
		'\x2', '\xBE', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC1', '\x5', 
		'\x1D', '\xF', '\x2', '\xC0', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xC0', 
		'\xC1', '\x3', '\x2', '\x2', '\x2', '\xC1', ' ', '\x3', '\x2', '\x2', 
		'\x2', '\xE', '\x2', 'k', 'y', '\x8D', '\x9B', '\xA1', '\xA3', '\xA8', 
		'\xAD', '\xB2', '\xB7', '\xC0', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
