//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\SicGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class SicGrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, INSTRUCCIONES=6, TIPODIRECTIVA=7, 
		BYTE=8, NUM=9, FINL=10, NUMH=11, NUMHH=12, ID=13, SEP=14, RSUB=15;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "INSTRUCCIONES", "TIPODIRECTIVA", 
		"BYTE", "NUM", "FINL", "NUMH", "NUMHH", "ID", "SEP", "RSUB"
	};


	public SicGrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SicGrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'START'", "'END'", "','", "' '", "'X'", null, null, null, null, 
		"'\n'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, "INSTRUCCIONES", "TIPODIRECTIVA", 
		"BYTE", "NUM", "FINL", "NUMH", "NUMHH", "ID", "SEP", "RSUB"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SicGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SicGrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x11', '\xCE', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', '|', '\n', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x5', '\b', '\x8A', '\n', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', 
		'\x9E', '\n', '\t', '\x3', '\n', '\x6', '\n', '\xA1', '\n', '\n', '\r', 
		'\n', '\xE', '\n', '\xA2', '\x3', '\n', '\x5', '\n', '\xA6', '\n', '\n', 
		'\x3', '\v', '\x3', '\v', '\x3', '\f', '\x6', '\f', '\xAB', '\n', '\f', 
		'\r', '\f', '\xE', '\f', '\xAC', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x6', '\xE', '\xB3', '\n', '\xE', '\r', '\xE', '\xE', '\xE', 
		'\xB4', '\x3', '\xE', '\a', '\xE', '\xB8', '\n', '\xE', '\f', '\xE', '\xE', 
		'\xE', '\xBB', '\v', '\xE', '\x6', '\xE', '\xBD', '\n', '\xE', '\r', '\xE', 
		'\xE', '\xE', '\xBE', '\x3', '\xF', '\x6', '\xF', '\xC2', '\n', '\xF', 
		'\r', '\xF', '\xE', '\xF', '\xC3', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x5', 
		'\x10', '\xCD', '\n', '\x10', '\x2', '\x2', '\x11', '\x3', '\x3', '\x5', 
		'\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', 
		'\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', 
		'\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '\x3', '\x2', '\x6', '\x4', 
		'\x2', '\x32', ';', '\x43', 'H', '\x4', '\x2', 'J', 'J', 'j', 'j', '\x4', 
		'\x2', '\x43', '\\', '\x63', '|', '\x4', '\x2', '\v', '\v', '\"', '\"', 
		'\x2', '\xF0', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x5', '\'', '\x3', '\x2', '\x2', '\x2', 
		'\a', '+', '\x3', '\x2', '\x2', '\x2', '\t', '-', '\x3', '\x2', '\x2', 
		'\x2', '\v', '/', '\x3', '\x2', '\x2', '\x2', '\r', '{', '\x3', '\x2', 
		'\x2', '\x2', '\xF', '\x89', '\x3', '\x2', '\x2', '\x2', '\x11', '\x8B', 
		'\x3', '\x2', '\x2', '\x2', '\x13', '\xA0', '\x3', '\x2', '\x2', '\x2', 
		'\x15', '\xA7', '\x3', '\x2', '\x2', '\x2', '\x17', '\xAA', '\x3', '\x2', 
		'\x2', '\x2', '\x19', '\xAE', '\x3', '\x2', '\x2', '\x2', '\x1B', '\xBC', 
		'\x3', '\x2', '\x2', '\x2', '\x1D', '\xC1', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', '\xC5', '\x3', '\x2', '\x2', '\x2', '!', '\"', '\a', 'U', '\x2', 
		'\x2', '\"', '#', '\a', 'V', '\x2', '\x2', '#', '$', '\a', '\x43', '\x2', 
		'\x2', '$', '%', '\a', 'T', '\x2', '\x2', '%', '&', '\a', 'V', '\x2', 
		'\x2', '&', '\x4', '\x3', '\x2', '\x2', '\x2', '\'', '(', '\a', 'G', '\x2', 
		'\x2', '(', ')', '\a', 'P', '\x2', '\x2', ')', '*', '\a', '\x46', '\x2', 
		'\x2', '*', '\x6', '\x3', '\x2', '\x2', '\x2', '+', ',', '\a', '.', '\x2', 
		'\x2', ',', '\b', '\x3', '\x2', '\x2', '\x2', '-', '.', '\a', '\"', '\x2', 
		'\x2', '.', '\n', '\x3', '\x2', '\x2', '\x2', '/', '\x30', '\a', 'Z', 
		'\x2', '\x2', '\x30', '\f', '\x3', '\x2', '\x2', '\x2', '\x31', '\x32', 
		'\a', '\x43', '\x2', '\x2', '\x32', '\x33', '\a', '\x46', '\x2', '\x2', 
		'\x33', '|', '\a', '\x46', '\x2', '\x2', '\x34', '\x35', '\a', '\x43', 
		'\x2', '\x2', '\x35', '\x36', '\a', 'P', '\x2', '\x2', '\x36', '|', '\a', 
		'\x46', '\x2', '\x2', '\x37', '\x38', '\a', '\x45', '\x2', '\x2', '\x38', 
		'\x39', '\a', 'Q', '\x2', '\x2', '\x39', ':', '\a', 'O', '\x2', '\x2', 
		':', '|', '\a', 'R', '\x2', '\x2', ';', '<', '\a', '\x46', '\x2', '\x2', 
		'<', '=', '\a', 'K', '\x2', '\x2', '=', '|', '\a', 'X', '\x2', '\x2', 
		'>', '|', '\a', 'L', '\x2', '\x2', '?', '@', '\a', 'L', '\x2', '\x2', 
		'@', '\x41', '\a', 'N', '\x2', '\x2', '\x41', '|', '\a', 'V', '\x2', '\x2', 
		'\x42', '\x43', '\a', 'L', '\x2', '\x2', '\x43', '\x44', '\a', 'I', '\x2', 
		'\x2', '\x44', '|', '\a', 'V', '\x2', '\x2', '\x45', '\x46', '\a', 'L', 
		'\x2', '\x2', '\x46', 'G', '\a', 'G', '\x2', '\x2', 'G', '|', '\a', 'S', 
		'\x2', '\x2', 'H', 'I', '\a', 'L', '\x2', '\x2', 'I', 'J', '\a', 'U', 
		'\x2', '\x2', 'J', 'K', '\a', 'W', '\x2', '\x2', 'K', '|', '\a', '\x44', 
		'\x2', '\x2', 'L', 'M', '\a', 'N', '\x2', '\x2', 'M', 'N', '\a', '\x46', 
		'\x2', '\x2', 'N', '|', '\a', '\x43', '\x2', '\x2', 'O', 'P', '\a', 'N', 
		'\x2', '\x2', 'P', 'Q', '\a', '\x46', '\x2', '\x2', 'Q', 'R', '\a', '\x45', 
		'\x2', '\x2', 'R', '|', '\a', 'J', '\x2', '\x2', 'S', 'T', '\a', 'N', 
		'\x2', '\x2', 'T', 'U', '\a', '\x46', '\x2', '\x2', 'U', '|', '\a', 'N', 
		'\x2', '\x2', 'V', 'W', '\a', 'N', '\x2', '\x2', 'W', 'X', '\a', '\x46', 
		'\x2', '\x2', 'X', '|', '\a', 'Z', '\x2', '\x2', 'Y', 'Z', '\a', 'O', 
		'\x2', '\x2', 'Z', '[', '\a', 'W', '\x2', '\x2', '[', '|', '\a', 'N', 
		'\x2', '\x2', '\\', ']', '\a', 'Q', '\x2', '\x2', ']', '|', '\a', 'T', 
		'\x2', '\x2', '^', '_', '\a', 'T', '\x2', '\x2', '_', '|', '\a', '\x46', 
		'\x2', '\x2', '`', '\x61', '\a', 'U', '\x2', '\x2', '\x61', '\x62', '\a', 
		'V', '\x2', '\x2', '\x62', '|', '\a', '\x43', '\x2', '\x2', '\x63', '\x64', 
		'\a', 'U', '\x2', '\x2', '\x64', '\x65', '\a', 'V', '\x2', '\x2', '\x65', 
		'\x66', '\a', '\x45', '\x2', '\x2', '\x66', '|', '\a', 'J', '\x2', '\x2', 
		'g', 'h', '\a', 'U', '\x2', '\x2', 'h', 'i', '\a', 'V', '\x2', '\x2', 
		'i', '|', '\a', 'N', '\x2', '\x2', 'j', 'k', '\a', 'U', '\x2', '\x2', 
		'k', 'l', '\a', 'V', '\x2', '\x2', 'l', 'm', '\a', 'U', '\x2', '\x2', 
		'm', '|', '\a', 'Y', '\x2', '\x2', 'n', 'o', '\a', 'U', '\x2', '\x2', 
		'o', 'p', '\a', 'V', '\x2', '\x2', 'p', '|', '\a', 'Z', '\x2', '\x2', 
		'q', 'r', '\a', 'U', '\x2', '\x2', 'r', 's', '\a', 'W', '\x2', '\x2', 
		's', '|', '\a', '\x44', '\x2', '\x2', 't', 'u', '\a', 'V', '\x2', '\x2', 
		'u', '|', '\a', '\x46', '\x2', '\x2', 'v', 'w', '\a', 'V', '\x2', '\x2', 
		'w', 'x', '\a', 'K', '\x2', '\x2', 'x', '|', '\a', 'Z', '\x2', '\x2', 
		'y', 'z', '\a', 'Y', '\x2', '\x2', 'z', '|', '\a', '\x46', '\x2', '\x2', 
		'{', '\x31', '\x3', '\x2', '\x2', '\x2', '{', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '{', '\x37', '\x3', '\x2', '\x2', '\x2', '{', ';', '\x3', '\x2', 
		'\x2', '\x2', '{', '>', '\x3', '\x2', '\x2', '\x2', '{', '?', '\x3', '\x2', 
		'\x2', '\x2', '{', '\x42', '\x3', '\x2', '\x2', '\x2', '{', '\x45', '\x3', 
		'\x2', '\x2', '\x2', '{', 'H', '\x3', '\x2', '\x2', '\x2', '{', 'L', '\x3', 
		'\x2', '\x2', '\x2', '{', 'O', '\x3', '\x2', '\x2', '\x2', '{', 'S', '\x3', 
		'\x2', '\x2', '\x2', '{', 'V', '\x3', '\x2', '\x2', '\x2', '{', 'Y', '\x3', 
		'\x2', '\x2', '\x2', '{', '\\', '\x3', '\x2', '\x2', '\x2', '{', '^', 
		'\x3', '\x2', '\x2', '\x2', '{', '`', '\x3', '\x2', '\x2', '\x2', '{', 
		'\x63', '\x3', '\x2', '\x2', '\x2', '{', 'g', '\x3', '\x2', '\x2', '\x2', 
		'{', 'j', '\x3', '\x2', '\x2', '\x2', '{', 'n', '\x3', '\x2', '\x2', '\x2', 
		'{', 'q', '\x3', '\x2', '\x2', '\x2', '{', 't', '\x3', '\x2', '\x2', '\x2', 
		'{', 'v', '\x3', '\x2', '\x2', '\x2', '{', 'y', '\x3', '\x2', '\x2', '\x2', 
		'|', '\xE', '\x3', '\x2', '\x2', '\x2', '}', '~', '\a', 'Y', '\x2', '\x2', 
		'~', '\x7F', '\a', 'Q', '\x2', '\x2', '\x7F', '\x80', '\a', 'T', '\x2', 
		'\x2', '\x80', '\x8A', '\a', '\x46', '\x2', '\x2', '\x81', '\x82', '\a', 
		'T', '\x2', '\x2', '\x82', '\x83', '\a', 'G', '\x2', '\x2', '\x83', '\x84', 
		'\a', 'U', '\x2', '\x2', '\x84', '\x8A', '\a', '\x44', '\x2', '\x2', '\x85', 
		'\x86', '\a', 'T', '\x2', '\x2', '\x86', '\x87', '\a', 'G', '\x2', '\x2', 
		'\x87', '\x88', '\a', 'U', '\x2', '\x2', '\x88', '\x8A', '\a', 'Y', '\x2', 
		'\x2', '\x89', '}', '\x3', '\x2', '\x2', '\x2', '\x89', '\x81', '\x3', 
		'\x2', '\x2', '\x2', '\x89', '\x85', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x10', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\a', '\x44', '\x2', 
		'\x2', '\x8C', '\x8D', '\a', '[', '\x2', '\x2', '\x8D', '\x8E', '\a', 
		'V', '\x2', '\x2', '\x8E', '\x8F', '\a', 'G', '\x2', '\x2', '\x8F', '\x90', 
		'\x3', '\x2', '\x2', '\x2', '\x90', '\x9D', '\x5', '\x1D', '\xF', '\x2', 
		'\x91', '\x92', '\a', '\x45', '\x2', '\x2', '\x92', '\x93', '\a', ')', 
		'\x2', '\x2', '\x93', '\x94', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', 
		'\x5', '\x1B', '\xE', '\x2', '\x95', '\x96', '\a', ')', '\x2', '\x2', 
		'\x96', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\a', 'Z', 
		'\x2', '\x2', '\x98', '\x99', '\a', ')', '\x2', '\x2', '\x99', '\x9A', 
		'\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\x5', '\x17', '\f', '\x2', 
		'\x9B', '\x9C', '\a', ')', '\x2', '\x2', '\x9C', '\x9E', '\x3', '\x2', 
		'\x2', '\x2', '\x9D', '\x91', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x97', 
		'\x3', '\x2', '\x2', '\x2', '\x9E', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'\x9F', '\xA1', '\t', '\x2', '\x2', '\x2', '\xA0', '\x9F', '\x3', '\x2', 
		'\x2', '\x2', '\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA0', 
		'\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\x3', '\x2', '\x2', '\x2', 
		'\xA3', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA6', '\t', '\x3', 
		'\x2', '\x2', '\xA5', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', 
		'\x3', '\x2', '\x2', '\x2', '\xA6', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'\xA7', '\xA8', '\a', '\f', '\x2', '\x2', '\xA8', '\x16', '\x3', '\x2', 
		'\x2', '\x2', '\xA9', '\xAB', '\t', '\x2', '\x2', '\x2', '\xAA', '\xA9', 
		'\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\x3', '\x2', '\x2', '\x2', 
		'\xAC', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\x3', '\x2', 
		'\x2', '\x2', '\xAD', '\x18', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', 
		'\x5', '\x17', '\f', '\x2', '\xAF', '\xB0', '\t', '\x3', '\x2', '\x2', 
		'\xB0', '\x1A', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB3', '\t', '\x4', 
		'\x2', '\x2', '\xB2', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB4', 
		'\x3', '\x2', '\x2', '\x2', '\xB4', '\xB2', '\x3', '\x2', '\x2', '\x2', 
		'\xB4', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB9', '\x3', '\x2', 
		'\x2', '\x2', '\xB6', '\xB8', '\x4', '\x32', ';', '\x2', '\xB7', '\xB6', 
		'\x3', '\x2', '\x2', '\x2', '\xB8', '\xBB', '\x3', '\x2', '\x2', '\x2', 
		'\xB9', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBA', '\x3', '\x2', 
		'\x2', '\x2', '\xBA', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xB9', 
		'\x3', '\x2', '\x2', '\x2', '\xBC', '\xB2', '\x3', '\x2', '\x2', '\x2', 
		'\xBD', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBC', '\x3', '\x2', 
		'\x2', '\x2', '\xBE', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xBF', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', '\xC0', '\xC2', '\t', '\x5', '\x2', '\x2', 
		'\xC1', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC3', '\x3', '\x2', 
		'\x2', '\x2', '\xC3', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', 
		'\x3', '\x2', '\x2', '\x2', '\xC4', '\x1E', '\x3', '\x2', '\x2', '\x2', 
		'\xC5', '\xC6', '\x5', '\x1D', '\xF', '\x2', '\xC6', '\xC7', '\a', 'T', 
		'\x2', '\x2', '\xC7', '\xC8', '\a', 'U', '\x2', '\x2', '\xC8', '\xC9', 
		'\a', 'W', '\x2', '\x2', '\xC9', '\xCA', '\a', '\x44', '\x2', '\x2', '\xCA', 
		'\xCC', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xCD', '\x5', '\x1D', '\xF', 
		'\x2', '\xCC', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCD', '\x3', 
		'\x2', '\x2', '\x2', '\xCD', ' ', '\x3', '\x2', '\x2', '\x2', '\x10', 
		'\x2', '{', '\x89', '\x9D', '\xA0', '\xA2', '\xA5', '\xAA', '\xAC', '\xB4', 
		'\xB9', '\xBE', '\xC3', '\xCC', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
